### ISSUE TITLE
Difficulty enabling features

### ISSUE THREAD

**Issue by Cam9731** [thebookisclosed/ViVe#104]
Hello. I'm new to vivetool and am having some difficulty enabling features. What i'm looking for specifically is the new file explorer layout (40950262,41076133). 

I run the command "vivetool /enable /id:40950262,41076133" and it says feature enabled successfully but nothing happens after a restart.

Prior to running the command, vivetool /query prints this for the specific id

![image](https://github.com/thebookisclosed/ViVe/assets/55032379/5e148739-1dfd-43d4-9b1e-11b67057278f)

After running, this is the output 

![image](https://github.com/thebookisclosed/ViVe/assets/55032379/fddb6338-e93c-4be4-abc0-b83358ecf8da)

Chances are I'm doing something stupid, please let me know what it is! Win ver shown below too for more information. 

Thanks!

![image](https://github.com/thebookisclosed/ViVe/assets/55032379/07425f46-9a1b-44a2-a0ab-5b6275e65630)

**Comment by thebookisclosed** [comment]
Higher priorities will always win over lower ones, meaning this feature will stay disabled unless you mess with registry. There is no API-based way of altering Priority 15 features and I don't intend to add workarounds for it.
Additionally, you're on zn_release. Even if you managed to enable the ID it would do nothing because the set of enable-able features in a *_release branch is greatly reduced.
