### ISSUE TITLE
[v0.2.1] Builds 1904x.1151+ don't respect Settings Value Banner feature

### ISSUE THREAD

**Issue by Mywebworx** [thebookisclosed/ViVe#15]
@thebookisclosed Vivetool V0.2.1, doesnt remove the Windows 10 settings banner, in Windows 10 2004, Build 19041.1151.

Please advise

**Comment by thebookisclosed** [comment]
This is most likely caused by Microsoft shifting the feature from a ByDefault state (meaning it has a default state which you are allowed to override) to an Always state, rendering ViVeTool useless for disabling it.
I will take a look in case they did something a little less mean such as changing the feature ID.

**Comment by Beerfloat** [comment]
Appreciate the update @thebookisclosed 
Hopefully this feature is still user configurable, somehow.

I just don't know what Microsoft is thinking. It is a giant eyesore.

**Comment by jnpl95** [comment]
Same, they keep insisting on putting ads in the OS itself, which we paid for. Absolutely ridiculous

**Comment by crim2som** [comment]
Hi @thebookisclosed, here is the description of my OS Build.
ViveTool v0.2.1, does not remove the Windows 10 settings banner, in Windows 10 2009, Build 19043.1151. 
This MS bloatware/malware applies to both Home and Pro which are both OS Build 19043.1151.  
Windows 10 21H1 Build 1904x.11xx (KB5004296 patch) was described as an optional extra, but now permanent feature. 
This MS Settings banner/header is very large and not wanted, there is no toggle off/on option. 
Malwarebytes does not remove this PUP malware. 
Look forward to getting toggle off/on option. Thanks.

**Comment by thebookisclosed** [comment]
KB5004296 changes the way the Settings Value Banner's enablement is checked.
In order to turn it off you'll need to disable feature **18299130** _as well as_ feature **31950543**.
Disabling the latter ID restores the old enablement checking behavior which in turns restores the relevancy of the former ID.

**Comment by Beerfloat** [comment]
Yeah ok, I can confirm.

[Admin prompt]:
vivetool addconfig 31950543 1
vivetool addconfig 12899130 1

[Reboot]
.. banner header gone on build 19043.1151

Nice find @thebookisclosed

**Comment by alwaysaheadofMS** [comment]
@thebookisclosed thank you, "disable feature 18299130 as well as feature 31950543" disabled the advertising banner!!! Appreciate it!!!!!

**Comment by Murkalael** [comment]
Mine doesn't work . 20H2 build 19042.1165 after update from KB5005033. 
But I manage to remove it by uninstalling the windows feature pack with dism.
dism / online /get-packages
find the user experience feature pack on the list copy its entire name
dism /online /remove-package /packagename:OneBigFeaturepackNameHere

it will ask if you want to reboot, once it does, banner is gone

**Comment by alwaysaheadofMS** [comment]
From what I am reading, the Windows User Feature Pack is essential for some functions to work properly in Windows now. I don't want to take the chance and remove it from one of my customers computers as I really don't know how essential it is for the OS! Are we supposed to jump through the hoops every few weeks due to another MS update to disable this moronic advertising? They know most people will tire of it and they will get their way!!

**Comment by Beerfloat** [comment]
The banners are still gone after update to 19043.1165 on my Windows 10 installations. Which also still have the ‘Windows Feature Experience Pack’.

**Comment by jnpl95** [comment]
> From what I am reading, the Windows User Feature Pack is essential for some functions to work properly in Windows now. I don't want to take the chance and remove it from one of my customers computers as I really don't know how essential it is for the OS! Are we supposed to jump through the hoops every few weeks due to another MS update to disable this moronic advertising? They know most people will tire of it and they will get their way!!

Windows OS Build: 19043.1165  Version: 21H1 Edition: Windows 10 Pro
The latest update, I managed to remove the banner doing what thebookisclosed suggested above
vivetool addconfig 31950543 1
vivetool addconfig 12899130 1

No need to disable the windows feature pack.

**Comment by Murkalael** [comment]
> From what I am reading, the Windows User Feature Pack is essential for some functions to work properly in Windows now. I don't want to take the chance and remove it from one of my customers computers as I really don't know how essential it is for the OS! Are we supposed to jump through the hoops every few weeks due to another MS update to disable this moronic advertising? They know most people will tire of it and they will get their way!!

Yes, feature pack is something they implemented so you don't tinker with things that they don't want you to mess with, like that annoying "News And Interests", Cortana and a bunch of things most don't want.

**Comment by alwaysaheadofMS** [comment]
> > From what I am reading, the Windows User Feature Pack is essential for some functions to work properly in Windows now. I don't want to take the chance and remove it from one of my customers computers as I really don't know how essential it is for the OS! Are we supposed to jump through the hoops every few weeks due to another MS update to disable this moronic advertising? They know most people will tire of it and they will get their way!!
> 
> Yes, feature pack is something they implemented so you don't tinker with things that they don't want you to mess with, like that annoying "News And Interests", Cortana and a bunch of things most don't want.

As time goes by, Microsoft will implement their profiling ads and intent, that will be integrated into the system, it's coming in Windows 11. Apple did this a long time ago.  I also removed "News and Interest", Cortana etc. but I am observing more and more hard coding into the OS. So far most of the options you have stated are removable for corporate clients but time is moving on! It's all about control. I used to read how people would disable so many services created for Vista, it turned out many of those services were absolutely required to be running to have the OS function correctly for most people's needs. Too many people jump at disabling and have no idea the repercussions. I would disable anything on my own machines, but now for clients. I don't want to spend the time getting those computers back at my expense. I wouldn't be in business for long.

**Comment by alwaysaheadofMS** [comment]
> > From what I am reading, the Windows User Feature Pack is essential for some functions to work properly in Windows now. I don't want to take the chance and remove it from one of my customers computers as I really don't know how essential it is for the OS! Are we supposed to jump through the hoops every few weeks due to another MS update to disable this moronic advertising? They know most people will tire of it and they will get their way!!
> 
> Windows OS Build: 19043.1165 Version: 21H1 Edition: Windows 10 Pro
> The latest update, I managed to remove the banner doing what thebookisclosed suggested above
> vivetool addconfig 31950543 1
> vivetool addconfig 12899130 1
> 
> No need to disable the windows feature pack.
> 
> EDIT: Sorry I thought you thought you needed to disable the feature pack to remove the banner. I agree with you completely that we shouldn't have to jump through all these hoops to disable the adverts

Thanks jnpl95, I forgot to restart the machine, after restarting the machine the ads were gone. On this end, no need to disable the windows feature pack., as you stated! :)

**Comment by thebookisclosed** [comment]
Most features require a reboot to have their new state fully reflected, I'm not sure why Microsoft decided to change most of their code to behave like this but they did.
Originally changes were instantenous but nowadays not so much.

For context: When the OS checks for the state of a feature, it also specifies if it wants the current state or the state it was in at boot, most internal feature checks opt for the latter these days.

**Comment by crim2som** [comment]
This remedy was good while it lasted. 
[Admin prompt]:
vivetool addconfig 31950543 1
vivetool addconfig 12899130 1

Microsoft have now updated their Settings header so that ViveTool v0.2.1 does not work on Windows 10 (x64) Version 2009 (build 19043.1165) version 21H1. There is no removal during live session or after Restart. 

Will there be an update? Thank you in anticipation.

**Comment by Beerfloat** [comment]
> Microsoft have now updated their Settings header so that ViveTool v0.2.1 does not work on Windows 10 (x64) Version 2009 (build 19043.1165) version 21H1. There is no removal during live session or after Restart.

Have you tried redoing it? I am running 8 Windows 10 Pro installations on various devices/VMs, and the header is still gone after upgrading to 19043.1165. Though I had to rerun vivetool/reboot on one of them.

**Comment by dogboon** [comment]
Following the above (copy/pasting as written),
vivetool addconfig 31950543 1
vivetool addconfig 12899130 1
worked for me, however I noticed that the feature number used for the header in the later post that I copied differed from the original:
128 etc vs 182 etc. That could account for crimson's lack of success.
Is it possible that my having applied the correct header fix previously (even though prior to reboot) had an effect that just needed the reverted enablement checking in order to take effect? 
Will play around with this if the header comes back.
(w10pro 21H1 build 19043.1165)

**Comment by crim2som** [comment]
Hi @dogboon your observation works. The second updated Admin prompt value is now wanted. Thank you. 
[Admin prompt]:
vivetool addconfig 31950543 1
vivetool addconfig 18299130 1

**Comment by Beerfloat** [comment]
That must have been a typo in a post of mine throwing people off, sorry. I updated it to avoid confusion.
@thebookisclosed always had the right value: 18299130 1

_If you had copy/pasted the wrong info, it would be undone by:
vivetool delconfig 12899130 1
(though it shouldn't matter)_

**Comment by alwaysaheadofMS** [comment]
I am finding it disappears for a day or so and comes back with the ads and nags!

**Comment by Beerfloat** [comment]
> I am finding it disappears for a day or so and comes back with the ads and nags! One of the latest updates keeps refreshing itself.

I'm not seeing this on my systems. When it's gone it's gone.

**Comment by Murkalael** [comment]
Ok, now here's the weirdest thing.  I recently installed windows 10 on 2 new machines on my work, the very first thing I did was try to remove the damn header and even with the 2 features listed here and reboot and even removing feature pack, it no longer has any effect, it still sits there. I tried with 21H2 - 19044.1288 and even an old 2004 compilation, they both behave same way.
vivetool addconfig 31950543 1
vivetool addconfig 18299130 1
no effect neither in command prompt nor powershell

**Comment by Beerfloat** [comment]
> Ok, now here's the weirdest thing. I recently installed windows 10 on 2 new machines on my work, the very first thing I did was try to remove the damn header and even with the 2 features listed here and reboot and even removing feature pack, it no longer has any effect, it still sits there. I tried with 21H2 - 19044.1288 and even an old 2004 compilation, they both behave same way. vivetool addconfig 31950543 1 vivetool addconfig 18299130 1 no effect neither in command prompt nor powershell

You need to run it in an admin level command prompt, and you need to reboot after running it.

Also, for a while the thing kept reappearing every few updates, at which point you'd have to redo the procedure, but lately it's gone back to staying gone.

**Comment by Murkalael** [comment]
I know that, always did that way. Still no luck. Funny thing other machines I did used back when I did my previous post on this topic are still without the banner, I was able to prevent them to come back disabling all tasks in the Floating folder of task scheduler.

**Comment by r-a-y** [comment]
Settings banner came back in the latest update (either KB5011487 or KB4023057). Tried the previous codes in this thread and they no longer work.

Are there any new codes to try?

**Comment by JoeMamaAME** [comment]
These:
```
vivetool addconfig 31950543 1
vivetool addconfig 18299130 1
```

Have no effect after installing the following update:
_2022-05 Cumulative Update for Windows 10 Version 21H2 for x64-based Systems (KB5013942)_

The previously working mach2 command I found for this also no longer work:
```
mach2 disable 18299130
```

**Comment by thebookisclosed** [comment]
There is no way to remove the banner in recent Windows 10 CUs, there's nothing ViVeTool can do to change this.

**Comment by Moopere** [comment]
> Mine doesn't work . 20H2 build 19042.1165 after update from KB5005033. But I manage to remove it by uninstalling the windows feature pack with dism. dism / online /get-packages find the user experience feature pack on the list copy its entire name dism /online /remove-package /packagename:OneBigFeaturepackNameHere
> 
> it will ask if you want to reboot, once it does, banner is gone

Good suggestion but doesn't work on 21H2 with update 19044.1766 (at least ... possibly even before).

tbh I still don't actually know what the experience feature packs actually do.  I uninstalled as per your suggestion above and nothing appears to be missing or different :)
