### ISSUE TITLE
[Feature Request] Create an Installer for this Tool

### ISSUE THREAD

**Issue by RudraSen2** [thebookisclosed/ViVe#61]
Hello, I want an Installer for this Tool because it increases the ease of use. I would like to contribute If I can. Thank You! Any Help is Appreciated.

**Comment by thebookisclosed** [comment]
How would an installer increase ease of use? It's a standalone tool that does not need any installing.

**Comment by RudraSen2** [comment]
Look, we have to first download the ZIP file, open an Administrator Command Prompt there, and then run your command. Plus we should have a feature for the auto-update also. An one-click installer would decreas some efforts.

**Comment by thebookisclosed** [comment]
Making an installer won't make the tool magically simpler to use than *any other command-line based tool*

The installer would at most place files for you, maybe create a command prompt shortcut that opens CMD and navigates to the drectory where the app files were extracted, but said things are trivial to do by yourself.

There is a slight learning curve to the tool specifically because it's not intended to be used by people who don't understand what it really changes under the hood.

**Comment by thebookisclosed** [comment]
> Personally disagree, if you are able to make the tool easier to use in installation, then more amount of people are able to use the tool effectively, from beginners to everyone else.

My point is that this tool is **not** for beginners, only for people on cutting edge builds that understand the implications of the edits the tool makes - hence the *deliberate* learning curve
