### ISSUE TITLE
Taskbar "never combine" stopped working after recent Windows 11 updates?

### ISSUE THREAD

**Issue by mloskot** [thebookisclosed/ViVe#80]
A month or two ago, I tried this https://twitter.com/thebookisclosed/status/1592981617341247490/photo/1 and `vivetool /enable /id:29785186 ` worked for me:

![MicrosoftTeams-image (2)](https://user-images.githubusercontent.com/80741/224008917-33e17dc0-30ac-4895-9efb-58da95baa7ee.png)

I recently installed fresh Windows 11 (22H2 (OS Build 22621.1344) and enabling this "never combine" feature no longer works for me - simply nothing happens/changes after restarts.

Has this feature been removed by recent Windows 11 updates?

p.s. Thank you for ViVe!

**Comment by thebookisclosed** [comment]
The image you've linked is of a Dev build (25246) with extra debugging laid on top to make the feature (barely) work.
To this day the feature hasn't been backported to production (builds 2262x) nor has it gotten any improvements in Dev (still identically broken in 25314.)
Enabling this feature in production does nothing as it's not present and enabling it in Dev using any standard means is impossible because it is blacklisted on a deeper level.

If you ever had an uncombined taskbar on Windows 11 you must have used 3rd party modifications, which the 2262x.13xx CU series can break as described by Known Issues in release notes: [February 28, 2023—KB5022913 (OS Build 22621.1344) Preview](https://support.microsoft.com/en-us/topic/february-28-2023-kb5022913-os-build-22621-1344-preview-3e38c0d9-924d-4f3f-b0b6-3bd49b2657b9)
`After installing this or later updates, Windows devices with some third-party UI customization apps might not start up.`

The screenshot of the feature "working" very much looks like the result of using either ExplorerPatcher to restore the Windows 10 taskbar, or simply disabling Shell Undocking (the mechanism through which a lot of the newer Windows 11 UI is hooked up), the cog button gives it away. The ability to disable Shell Undocking has been removed over time as far as I'm aware.

Considering you mentioned that this is a fresh install, you'll want to reinstate whichever mod you've been using before and make sure it's up to date to comply with the newest CU changes. It's definitely not something enabled through ViVe.

**Comment by mloskot** [comment]
> The screenshot of the feature "working" very much looks like the result of using either ExplorerPatcher to restore the Windows 10 taskbar,

I've done retrospective double-check and I looks like I had used the ExplorerPatcher indeed!

After discovering your announcement on tweeter, I web searched a bit more discovering tools like https://github.com/PeterStrick/ViVeTool-GUI and https://github.com/PeterStrick/ViVeTool-GUI, and wrongly assumed they are all facades based on your work on the ViVe tool, eventually using the ExplorerPatcher. My mistake.

Thank you very much for the detailed explanation of my problem. I think this can be closed now.
