### ISSUE TITLE
completely remove

### ISSUE THREAD

**Issue by sakmak07** [thebookisclosed/ViVe#81]
How can i completely remove vivetool from my pc?

**Comment by TheCommentatorPlus** [comment]
Just drag and drop vivetool into your recycle bin, easy!

**Comment by thebookisclosed** [comment]
ViVeTool is a standalone program, it does not get "installed" in any shape or form. It's like asking how to remove regedit hoping it would undo registry changes you made but don't want anymore.

To get rid of the overrides you've put in place you'll want to use the `/fullreset` command. This is however not functional in newest production and Dev builds due to slight changes to the underlying feature mechanism in Windows, my apologies.

An update that's coming later this week will address the issue. Feel free to give the command a try, you might be on an old enough revision for it to still work. In case it doesn't it won't break anything.

**Comment by sakmak07** [comment]
> Just drag and drop vivetool into your recycle bin, easy!

Already did, that didn't work 😅

**Comment by sakmak07** [comment]
> ViVeTool is a standalone program, it does not get "installed" in any shape or form. It's like asking how to remove regedit hoping it would undo registry changes you made but don't want anymore.
> 
> To get rid of the overrides you've put in place you'll want to use the `/fullreset` command. This is however not functional in newest production and Dev builds due to slight changes to the underlying feature mechanism in Windows, my apologies.
> 
> An update that's coming later this week will address the issue. Feel free to give the command a try, you might be on an old enough revision for it to still work. In case it doesn't it won't break anything.

I just downloaded latest version yesterday, guess it won't work but I could wait. I tried uninstalling and reinstalling latest win11 update thinking it would solve anything but it didn't either.

**Comment by sakmak07** [comment]
> ViVeTool is a standalone program, it does not get "installed" in any shape or form. It's like asking how to remove regedit hoping it would undo registry changes you made but don't want anymore.
> 
> To get rid of the overrides you've put in place you'll want to use the `/fullreset` command. This is however not functional in newest production and Dev builds due to slight changes to the underlying feature mechanism in Windows, my apologies.
> 
> An update that's coming later this week will address the issue. Feel free to give the command a try, you might be on an old enough revision for it to still work. In case it doesn't it won't break anything.

so what's going on? it's been more than two weeks.

**Comment by thebookisclosed** [comment]
v0.3.3 with a fix for the issue is now out.
